version: '3'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#          DEV          #
#########################

services:

    hotel_service:
        build:
            context: ./docker/
            args:
                - "DOCKER_USER=${DOCKER_USER}"
                - "NODE_PORT=${NODE_INTERNAL_PORT}"
        restart: "${RESTART_POLICIES}"
        links:
            - "mongo:mongo"
        volumes:
            - ".:/home/docker:rw"
        working_dir: "/home/docker"
        user: "${DOCKER_USER}"
        ports:
            - "${NODE_EXTERNAL_PORT}:${NODE_INTERNAL_PORT}"

    mongo:
        image: mongo
        restart: "${RESTART_POLICIES}"
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - "./.data/db:/data/db:Z"

    mongo_express:
        image: mongo-express
        restart: "${RESTART_POLICIES}"
        links:
            - "mongo:mongo"
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"
        environment:
            - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
            - "ME_CONFIG_BASICAUTH_USERNAME=etna"
            - "ME_CONFIG_BASICAUTH_PASSWORD=devops"
